### ISSUE TITLE
About Android BluePill /EmulatorAntiDetect

### ISSUE THREAD

**Issue by ajinabraham** [MindMac/HideAndroidEmulator#1]
Hey @MindMac I am using https://github.com/idanr1986/cuckoo-droid/blob/master/utils/android_emulator_creator/hooking/EmulatorAntiDetect.apk in https://github.com/ajinabraham/Mobile-Security-Framework-MobSF for Emulator Anti-VM check bypass.
I wanted to credit the author not sure who authored this Xposed module. I see similar source code here: https://github.com/MindMac/HideAndroidEmulator/tree/master/HITCON/DemoCode

Are you the author of this module? If not, do you have any idea on the source/author of this xposed module?

**Comment by MindMac** [comment]
Hi, I am the author of the HideAndroidEmulator project, but I don't know if the EmulatorAntiDetect.apk from cuckoo-droid is the same as I developed.

**Comment by ajinabraham** [comment]
Thanks for confirming. So it looks like you are the author of https://github.com/MindMac/HideAndroidEmulator/tree/master/HITCON/DemoCode/EmulatorAntiDetect
It's a nice module. Thanks for your work

**Comment by amiCrAzyADi** [comment]
When I am trying to open Bluepill It is showing " This Module Doesn't provide User Interface " !!
